
title: "Chronopsychiatry Research Group"
description: "Integrating research and clinical expertise in mental health and circadian science"
email : "chronopsychiatry@ed.ac.uk"
wiki : "https://www.wiki.ed.ac.uk/display/CHRON"
github:
  is_project_page: false
  
